plugins:
  - jekyll-sitemap

exclude:
  - docs/*
  - apps/*
  - backup/*
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
  - tsconfig.json

include:
  - apps/landing/out
  - apps/pwa/dist