plugins:
  - jekyll-sitemap

exclude:
  - docs/*
  - packages/*
  - backup/*
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
  - tsconfig.json

include:
  - packages/landing/out
  - packages/pwa/dist